#pragma once

DECLARE_MULTICAST_DELEGATE(FOnCharacterStartedInteractionHandle)
DECLARE_MULTICAST_DELEGATE(FOnCharacterStartedSpecialInteractionHandle)
DECLARE_MULTICAST_DELEGATE(FOnKitchenObjectAddedHandle)

